#include<iostream>

using namespace std;

int main()
{
    char *str1,*str2;
    
     
   cin>>
    if (strlen(str1)!= strlen(str2))
    {
       cout<<"no match";
    }
    else
    {
         for(i=0;i<strlen(str1);i++)
         {
            if (*(str1+i) == *(str2+i))
            continue;
            else
            {
                cout<<"no match";
            }
         }
   }
    
    
    

}
